name: test-not-found-fails

on: 
  workflow_dispatch:

jobs:
  test-find-api:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - id: find-api-fails
        uses: ./
        continue-on-error: true
        with:
          apigw-url: ${{ secrets.APIGW_URL }}
          apigw-user: ${{ secrets.APIGW_USERNAME }}
          apigw-password: ${{ secrets.APIGW_PASSWORD }}
          api-name: 'Swagger Petstore'
          api-version: '1.0.7'
      - name: check-failed
        run: | 
          echo "outcome:    ${{ steps.find-api-fails.outcome }}"
          echo "conclusion: ${{ steps.find-api-fails.conclusion }}"